{
 "title": "BMS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT Voltage, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT Voltage, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1\n\n",
     "rawQueryText": "WITH converted AS (\n   SELECT Voltage, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT Voltage, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1\n\n",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT Watts, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT Watts, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "rawQueryText": "WITH converted AS (\n   SELECT Watts, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT Watts, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT Amps, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT Amps, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1\n",
     "rawQueryText": "WITH converted AS (\n   SELECT Amps, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT Amps, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1\n",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "SOC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT StateOfCharge, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT StateOfCharge, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "rawQueryText": "WITH converted AS (\n   SELECT StateOfCharge, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT StateOfCharge, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT StateOfCharge as B1SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0 \n) \nSELECT B1SOC as 'Battery 1 SOC', datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1\n",
     "rawQueryText": "WITH converted AS (\n   SELECT StateOfCharge as B1SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0 \n) \nSELECT B1SOC as 'Battery 1 SOC', datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT StateOfCharge as B2SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1 \n) \nSELECT B2SOC as 'Battery 2 SOC', datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "rawQueryText": "WITH converted AS (\n   SELECT StateOfCharge as B2SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1 \n) \nSELECT B2SOC as 'Battery 2 SOC', datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Cell High",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT CellVoltageHigh, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT CellVoltageHigh, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "rawQueryText": "WITH converted AS (\n   SELECT CellVoltageHigh, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT CellVoltageHigh, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Cell Low",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT CellVoltageLow, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT CellVoltageLow, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "rawQueryText": "WITH converted AS (\n   SELECT CellVoltageLow, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT CellVoltageLow, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Cell Difference",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT CellVoltageDelta, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT CellVoltageDelta, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "rawQueryText": "WITH converted AS (\n   SELECT CellVoltageDelta, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \n) \nSELECT CellVoltageDelta, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds} order by datetime desc LIMIT 1",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Volts" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   -- a row looks like this (value, date): 1.45, '2020-12-12'\r\n   SELECT Voltage as BMSVoltage, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings\r\n)\r\nSELECT datetime, BMSVoltage FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\r\n   -- a row looks like this (value, date): 1.45, '2020-12-12'\r\n   SELECT Voltage as BMSVoltage, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings\r\n)\r\nSELECT datetime, BMSVoltage FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "-- select \n-- strftime('%s', DateTime) as timestamp,\n-- CAST(BatteryVoltage AS FLOAT) as BV1\n-- from BatteryReadings\n-- where SlaveNumber = 0\nWITH converted AS (\n   -- a row looks like this (value, date): 1.45, '2020-12-12'\n   SELECT BatteryVoltage as B1V,  CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n)\nSELECT datetime, B1V FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "-- select \n-- strftime('%s', DateTime) as timestamp,\n-- CAST(BatteryVoltage AS FLOAT) as BV1\n-- from BatteryReadings\n-- where SlaveNumber = 0\nWITH converted AS (\n   -- a row looks like this (value, date): 1.45, '2020-12-12'\n   SELECT BatteryVoltage as B1V,  CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n)\nSELECT datetime, B1V FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   SELECT Amps as BMSCurrent,  CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings\r\n)\r\nSELECT datetime, BMSCurrent FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "rawQueryText": "WITH converted AS (\r\n   SELECT Amps as BMSCurrent,  CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings\r\n)\r\nSELECT datetime, BMSCurrent FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT BatteryCurrent as BC1,  CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n)\nSELECT datetime, BC1 FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT BatteryCurrent as BC1,  CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n)\nSELECT datetime, BC1 FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT BatteryCurrent as BC2, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n)\nSELECT datetime, BC2 FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT BatteryCurrent as BC2, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n)\nSELECT datetime, BC2 FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   SELECT CellVoltageHigh as B1H, CellVoltageLow as B1L, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0 and B1H > 0 and B1L > 0\r\n) \r\nSELECT B1H, B1L, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "rawQueryText": "WITH converted AS (\r\n   SELECT CellVoltageHigh as B1H, CellVoltageLow as B1L, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0 and B1H > 0 and B1L > 0\r\n) \r\nSELECT B1H, B1L, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT CellVoltageHigh as B2H, CellVoltageLow as B2L, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1 and B2H > 0 and B2L > 0\n) \nSELECT B2H, B2L, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT CellVoltageHigh as B2H, CellVoltageLow as B2L, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1 and B2H > 0 and B2L > 0\n) \nSELECT B2H, B2L, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Current Limiter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   SELECT CurrentLimit, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT CurrentLimit, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "rawQueryText": "WITH converted AS (\r\n   SELECT CurrentLimit, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT CurrentLimit, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT CurrentLimit as B1CL, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1CL, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT CurrentLimit as B1CL, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1CL, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT CurrentLimit as B2CL, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2CL, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT CurrentLimit as B2CL, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2CL, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Cell Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   SELECT CellVoltageDelta as BmsCellDiff, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT BmsCellDiff, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "rawQueryText": "WITH converted AS (\r\n   SELECT CellVoltageDelta as BmsCellDiff, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT BmsCellDiff, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\r\n   SELECT CellVoltageDelta as B1CellDiff, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\r\n) \r\nSELECT B1CellDiff, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n\r\n",
     "rawQueryText": "WITH converted AS (\r\n   SELECT CellVoltageDelta as B1CellDiff, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\r\n) \r\nSELECT B1CellDiff, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n\r\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\r\n   SELECT CellVoltageDelta as B2CellDiff, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\r\n) \r\nSELECT B2CellDiff, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\r\n   SELECT CellVoltageDelta as B2CellDiff, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\r\n) \r\nSELECT B2CellDiff, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "BMS temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   SELECT BmsTemperatureHigh as BMSH,BmsTemperatureLow as BMSL,Temperature as BMST, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT BMSH, BMSL, BMST, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n\r\n",
     "rawQueryText": "WITH converted AS (\r\n   SELECT BmsTemperatureHigh as BMSH,BmsTemperatureLow as BMSL,Temperature as BMST, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT BMSH, BMSL, BMST, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n\r\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT TemperatureOne as B1T1,TemperatureTwo as B1T2,TemperatureMos B1TMOS, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0 \n) \nSELECT B1T1, B1T2, B1TMOS, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT TemperatureOne as B1T1,TemperatureTwo as B1T2,TemperatureMos B1TMOS, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0 \n) \nSELECT B1T1, B1T2, B1TMOS, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT TemperatureOne as B2T1,TemperatureTwo as B2T2,TemperatureMos B2TMOS, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1 \n) \nSELECT B2T1, B2T2, B2TMOS, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT TemperatureOne as B2T1,TemperatureTwo as B2T2,TemperatureMos B2TMOS, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1 \n) \nSELECT B2T1, B2T2, B2TMOS, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "State of charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\r\n   SELECT StateOfCharge, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT StateOfCharge, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n\r\n",
     "rawQueryText": "WITH converted AS (\r\n   SELECT StateOfCharge, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BmsReadings \r\n) \r\nSELECT StateOfCharge, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n\r\n",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT StateOfCharge as B1SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1SOC, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT StateOfCharge as B1SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1SOC, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT StateOfCharge as B2SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2SOC, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT StateOfCharge as B2SOC, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2SOC, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  },
  {
   "title": "Discharge and Charge Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n   SELECT DischargedTotal as B1DCT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1DCT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT DischargedTotal as B1DCT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1DCT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT DischargedTotal as B2DCT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2DCT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT DischargedTotal as B2DCT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2DCT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT ChargedTotal as B1CT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1CT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT ChargedTotal as B1CT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 0\n) \nSELECT B1CT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    },
    {
     "queryText": "WITH converted AS (\n   SELECT ChargedTotal as B2CT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2CT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "rawQueryText": "WITH converted AS (\n   SELECT ChargedTotal as B2CT, CAST(strftime('%s', DateTime) as integer) AS datetime FROM BatteryReadings where SlaveNumber = 1\n) \nSELECT B2CT, datetime FROM converted WHERE datetime BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [ "datetime" ]
    }
   ]
  }
 ]
}