{
 "title": "InfluxDB Deye Mod",
 "time": { "from": "2023-07-31T03:35:59.777Z", "to": "2023-07-31T03:42:56.830Z" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"Amps\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Voltage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.Voltage", "name": "BMS" },
      { "jsonPath": "$.Batteries[0].Voltage", "language": "jsonpath", "name": "Batt 1" },
      { "jsonPath": "$.Batteries[1].Voltage", "language": "jsonpath", "name": "Batt 2" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.Amp", "name": "BMS" },
      { "jsonPath": "$.Batteries[0].Current", "language": "jsonpath", "name": "Batt 1" },
      { "jsonPath": "$.Batteries[1].Current", "language": "jsonpath", "name": "Batt 2" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.Watts" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Cells",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.Batteries[0].CellLow", "name": "B1 L" },
      { "jsonPath": "$.Batteries[0].CellHigh", "language": "jsonpath", "name": "B1 H" },
      { "jsonPath": "$.Batteries[0].CellDelta", "language": "jsonpath", "name": "B1 Diff" },
      { "jsonPath": "$.Batteries[1].CellLow", "language": "jsonpath", "name": "B2 L" },
      { "jsonPath": "$.Batteries[1].CellHigh", "language": "jsonpath", "name": "B2 H" },
      { "jsonPath": "$.Batteries[1].CellDelta", "language": "jsonpath", "name": "B2 Diff" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "State of charge",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.SOC", "name": "BMS", "type": "number" }
     ],
     "method": "GET"
    },
    {
     "fields": [
      { "jsonPath": "$.Batteries[0].StateOfCharge", "name": "Batt 1", "type": "number" },
      { "jsonPath": "$.Batteries[1].StateOfCharge", "language": "jsonpath", "name": "Batt 2", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Battery 1 Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"cellVoltages\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryCellReading\" and r.BatteryNumber == \"0\")\r\n  |> filter(fn: (r) => r._field == \"Cell01\" or r._field == \"Cell02\" or r._field == \"Cell03\" or r._field == \"Cell04\" or r._field == \"Cell05\" or r._field == \"Cell06\" or r._field == \"Cell07\" or r._field == \"Cell08\" \r\n                    or r._field == \"Cell09\" or r._field == \"Cell10\" or r._field == \"Cell11\" or r._field == \"Cell12\" or r._field == \"Cell13\" or r._field == \"Cell14\" or r._field == \"Cell15\" or r._field == \"Cell16\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageHigh\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageLow\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery 2 Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"cellVoltages\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryCellReading\" and r.BatteryNumber == \"1\")\r\n  |> filter(fn: (r) => r._field == \"Cell01\" or r._field == \"Cell02\" or r._field == \"Cell03\" or r._field == \"Cell04\" or r._field == \"Cell05\" or r._field == \"Cell06\" or r._field == \"Cell07\" or r._field == \"Cell08\" \r\n                    or r._field == \"Cell09\" or r._field == \"Cell10\" or r._field == \"Cell11\" or r._field == \"Cell12\" or r._field == \"Cell13\" or r._field == \"Cell14\" or r._field == \"Cell15\" or r._field == \"Cell16\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"Watts\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryCurrent\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryVoltage\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"Amps\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryCurrent\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Limiter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"CurrentLimit\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CurrentLimit\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Discharge/charge totals and cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"DischargedTotal\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"ChargedTotal\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "State of charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"StateOfCharge\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"StateOfCharge\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cell Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageDelta\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageDelta\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"Voltage\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryVoltage\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BMS temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"TemperatureMos\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"TemperatureOne\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"TemperatureTwo\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}