{
 "title": "InfluxDB Deye",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 } },
  { "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 } },
  { "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 } },
  { "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 } },
  {
   "title": "State of charge",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.SOC", "name": "BMS", "type": "number" }
     ],
     "method": "GET"
    },
    {
     "fields": [
      { "jsonPath": "$.Batteries[0].StateOfCharge", "name": "Batt 1", "type": "number" },
      { "jsonPath": "$.Batteries[1].StateOfCharge", "language": "jsonpath", "name": "Batt 2", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"Voltage\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryVoltage\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageHigh\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageLow\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cell Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageDelta\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CellVoltageDelta\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"Watts\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryCurrent\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryVoltage\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"Amps\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"BatteryCurrent\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Limiter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"CurrentLimit\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"CurrentLimit\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Discharge/charge totals and cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"DischargedTotal\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"ChargedTotal\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "State of charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BmsReading\")\r\n  |> filter(fn: (r) => r._field == \"StateOfCharge\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"StateOfCharge\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BMS temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"TemperatureMos\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"TemperatureOne\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"bmsReadings\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"BatteryReading\")\r\n  |> filter(fn: (r) => r._field == \"TemperatureTwo\")\r\n  |> aggregateWindow(every: 4s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}